"""professional_kitchen

Revision ID: 83833069a823
Revises: 23349b17ff17
Create Date: 2026-09-05 00:37:23.219608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83833069a823'
down_revision = '23349b17ff17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_expires_at'), ['expires_at'], unique=False)

    op.create_table('production_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('batches', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('production_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ingredientes_receta', schema=None) as batch_op:
        batch_op.alter_column('cantidad_necesaria',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.alter_column('rinde',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None, naming_convention={'uq': 'uq_%(table_name)s_%(column_0_name)s'}) as batch_op:
        batch_op.add_column(sa.Column('auth_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_demo', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        for constraint in sa.inspect(op.get_bind()).get_unique_constraints('user'):
            if constraint['column_names'] == ['address']:
                batch_op.drop_constraint(constraint['name'] or 'uq_user_address', type_='unique')
        batch_op.add_column(sa.Column('reset_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.alter_column('cantidad_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
        batch_op.alter_column('minimo_stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.alter_column('cantidad_inventario',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)
        batch_op.alter_column('cantidad_inventario_minimo',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.alter_column('cantidad_inventario_minimo',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cantidad_inventario',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.alter_column('minimo_stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cantidad_stock',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_expires_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_demo')
        batch_op.drop_column('auth_version')

    with op.batch_alter_table('receta', schema=None) as batch_op:
        batch_op.alter_column('rinde',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('ingredientes_receta', schema=None) as batch_op:
        batch_op.alter_column('cantidad_necesaria',
               existing_type=sa.Numeric(precision=14, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('production_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_log_user_id'))

    op.drop_table('production_log')
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_expires_at'))

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
