"""kitchen_uniqueness

Revision ID: 916fef3768ae
Revises: 83833069a823
Create Date: 2026-09-05 01:01:35.176836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916fef3768ae'
down_revision = '83833069a823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kitchen_ingredient', ['user_id', 'materias_primas_id'])

    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kitchen_product', ['user_id', 'receta_id'])

    with op.batch_alter_table('user_receta', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_kitchen_recipe', ['user_id', 'receta_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_receta', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kitchen_recipe', type_='unique')

    with op.batch_alter_table('user_producto_final', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kitchen_product', type_='unique')

    with op.batch_alter_table('user_materias_primas', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kitchen_ingredient', type_='unique')

    # ### end Alembic commands ###
